"""New relationship update

Revision ID: 602b026d5245
Revises: ffc600560054
Create Date: 2025-08-04 15:53:47.751672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602b026d5245'
down_revision: Union[str, Sequence[str], None] = 'ffc600560054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'study_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'study_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
