"""New column in StudyGroup

Revision ID: 86a322839e38
Revises: 602b026d5245
Create Date: 2025-08-04 16:05:33.058162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a322839e38'
down_revision: Union[str, Sequence[str], None] = '602b026d5245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studygroups', sa.Column('count_students', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studygroups', 'count_students')
    # ### end Alembic commands ###
