"""New column in Student patronymic

Revision ID: 8da317f26733
Revises: 2f01505fd593
Create Date: 2025-08-04 17:12:08.617264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da317f26733'
down_revision: Union[str, Sequence[str], None] = '2f01505fd593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('patronymic', sa.String(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'patronymic')
    # ### end Alembic commands ###
