"""New relationship

Revision ID: ffc600560054
Revises: 96cffd31490b
Create Date: 2025-08-04 15:39:34.270969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc600560054'
down_revision: Union[str, Sequence[str], None] = '96cffd31490b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('study_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'studygroups', ['study_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'study_group_id')
    # ### end Alembic commands ###
